theme = "autumn"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
completion-trigger-len = 1
bufferline = "multiple"
idle-timeout = 0
auto-format = true
#rulers = [80]
true-color = true


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "diagnostics"]
right = ["total-line-numbers", "primary-selection-length", "position"]
separator = "│"
